MajaTours/Controllers/CategoriesController.cs
using MajaTours.Data;
using MajaTours.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MajaTours.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {
        
        //CONSTRUCTOR PARA INYECTAR A LA BASE DE DATOS.
            private readonly DataContext _context;
            public CategoriesController(DataContext context)
            {
                _context = context;

            }
        // FIN

        // CONTROLADOR PARA LA VISTA INDEX.
            public async Task<IActionResult> Index()
            {
                return View(await _context.categories.ToListAsync());
            }
        // FIN.

        // CONTROLADOR CREAR UNA NUEVA GATEGORIA.
            public IActionResult Create()
            {
                return View();
            }
            
            // INICIO DEL METODO POST: PARA ENVIAR DATOS A LA BASE DE DATOS Y VALIDAR LOS CAMPOS.
                [HttpPost]
                [ValidateAntiForgeryToken]
                public async Task<IActionResult> Create( Category category)
                {
                    if (ModelState.IsValid) //Que cumpla con data anotetions
                    {
                        _context.Add(category);

                        //VALIDACION PARA NO PERMITIR REPETIR LA MISMA CATEGORIA. 
                            try
                            {
                                await _context.SaveChangesAsync();
                                return RedirectToAction(nameof(Index));
                            }
                            catch (DbUpdateException dbUpdateException)
                            {
                                if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                                {
                                    ModelState.AddModelError(string.Empty, "Ya existe una categoria con el mismo nombre.");
                                }
                                else{
                                    ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                                }
                            }
                            catch (Exception exception)
                            {
                                ModelState.AddModelError(string.Empty, exception.Message);
                            }
                        // FIN DE VALIDACION DE CATEGORIA.
                    }
                    return View(category);
                }
            // FIN DEL METODO POST PARA CATEGORIA
        // FIN DE CREAR UNA GATEGORIA NUEVA
        
        // CONTROLADOR EDITAR UNA CATEGORIA
            // INICIO DEL METODO GET: PARA EDITAR LA CATEGORÍA.
                public async Task<IActionResult> Edit(int? id) // El id es un parametro
                {
                    if (id == null || _context.categories == null)
                    {
                        return NotFound();
                    }
                    
                    var category = await _context.categories.FindAsync(id);
                    if (category == null)
                    {
                        return NotFound();
                    }
                    return View(category);
                }
            // FIN
            
            // INICIO DEL METODO POST: PARA ENVIAR DATOS A LA BASE DE DATOS Y VALIDAR LOS CAMPOS.
                [HttpPost]
                [ValidateAntiForgeryToken]
                public async Task<IActionResult> Edit(int id,Category category)
                {
                    if (id != category.Id)
                    {
                        return NotFound();
                    }
                    if (ModelState.IsValid) // si el modelo es valido.
                    {
                        //VALIDACION PARA NO REPETIR LA MISMA CATEGORIA. 
                        try
                        {
                            _context.Update(category);
                            await _context.SaveChangesAsync();
                            return RedirectToAction(nameof(Index));
                        }
                        catch (DbUpdateException dbUpdateException)
                        {
                            if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                            {
                                ModelState.AddModelError(string.Empty, "Ya existe una categoría con el mismo nombre.");
                            }
                            else
                            {
                                ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                            }
                        }
                        catch (Exception exception)
                        {
                            ModelState.AddModelError(string.Empty, exception.Message);
                        }
                    }
                    return View(category);
                }
            // FIN DEL METODO POST PARA EDITAR LA CATEGORIA
        // FIN DE CONTROLARDOR PARA EDITAR UNA CATEGORIA.

        // CONTROLADOR PARA MOSTRAR UN DETALLE PARA CATEGORIA.
            public async Task<IActionResult> Details(int? id)
            {
                if (id == null || _context.categories == null)
                {
                    return NotFound();
                }
                var category = await _context.categories
                .FirstOrDefaultAsync(m => m.Id == id);
                if (category == null)
                {
                    return NotFound();
                }
                return View(category);
            }
        // FIN DEL METODO GET, DEL DETALLE

       
        // CONTROLADOR PARA ELMINAR UNA CATEGORÍA

            // METODO GET PARA MOSTRAR UNA CATEGORIA
            public async Task<IActionResult> Delete(int? id)
            {
                if (id == null || _context.categories == null)
                {
                    return NotFound();
                }
                var category = await _context.categories
                .FirstOrDefaultAsync(m => m.Id == id);
                if (category == null)
                {
                    return NotFound();
                }
                return View(category);
            }

             // INICIO DEL METODO POST : PARA ELMINAR POR COMPLETO LOS DATOS DE UNA CATEGORÍA
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> DeleteConfirmed(int id)
            {
                if (_context.categories == null)
                {
                    return Problem("Entity set 'DataContext.Country'  is null.");
                }
                var category = await _context.categories.FindAsync(id);
                if (category != null)
                {
                    _context.categories.Remove(category);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
        
        // FIN DEL CONTROLADOR PARA ELIMINAR UNA CATEGORIA.  
    }
}

MajaTours/Controllers/ProductsController.cs
using MajaTours.Data;
using MajaTours.Data.Entities;
using MajaTours.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MajaTours.Controllers
{

    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private readonly DataContext _context;

        //INYECCIÓN A LA BASE DE DATOS.
        public ProductsController(DataContext context)
        {
            _context = context;
        }  
        public async Task<IActionResult> Index()
        {
        //listar
            var listarProductos = _context.Products.ToList();
            return View(listarProductos);
            //listar
        }

        //MOSTRAR PRODUCTOS A LA VISTA INDEX.
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                Product product = new()
                {
                    Description = model.Description,
                    Name = model.Name,
                    Price = model.Price,
                    Image = model.Image
                };
                try
                {
                    _context.Add(product);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        ModelState.AddModelError(string.Empty, "Ya existe un producto con el mismo nombre.");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    } 
                }
                    catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }
            return View(model);
        }

        //-------- EDITAR PRODUCTO -------------//
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
             
            Product product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            
            EditProductViewModel model = new()
            {
                Description = product.Description,
                Id = product.Id,
                Name = product.Name,
                Price = product.Price,
                Image = product.Image
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CreateProductViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            try
            {
                Product product = await _context.Products.FindAsync(model.Id);
                product.Description = model.Description;
                product.Name = model.Name;
                product.Price = model.Price;
                product.Image = model.Image;
                _context.Update(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException dbUpdateException)
            {
                if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                {
                    ModelState.AddModelError(string.Empty, "Ya existe un producto con el mismo nombre.");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                }
            }
            catch (Exception exception)
            {
                ModelState.AddModelError(string.Empty, exception.Message);
            }
            return View(model);
        }  

        // DETALLES DE UN PRODUCTO.
            public async Task<IActionResult> Details(int? id)
            {
                if (id == null)
                {
                    return NotFound();
                }
                
                Product product = await _context.Products
                //.Include(p => p.Image)
                .FirstOrDefaultAsync(p => p.Id == id);
                if (product == null)
                {
                    return NotFound();
                }
                return View(product);
            }
        //.  

        // ELIMINAR PRODUSCTOS.
            public async Task<IActionResult> Delete(int? id)
            {
                if (id == null)
                {
                    return NotFound();
                }
                Product product = await _context.Products
                .FirstOrDefaultAsync(p => p.Id == id);
                if (product == null)
                {
                    return NotFound();
                }
                return View(product);
            }

            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> DeleteConfirmed(int id)
            {
                Product product = await _context.Products
                    .FirstOrDefaultAsync(p => p.Id == id);
                    
                _context.Products.Remove(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

        //¡
    }
}

MajaTours/Controllers/UsersController.cs
using MajaTours.Data;
using MajaTours.Data.Entities;
using MajaTours.Helpers;
using MajaTours.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MajaTours.Controllers
{
    [Authorize(Roles="Admin")]
    public class UsersController : Controller
    {
        private readonly IUserHelper _userHelper;
        private readonly DataContext _context;

        //------------ INYECCIÓN A LA BASE DE DATOS -----------
        public UsersController(IUserHelper userHelper, DataContext context)
            {
            _userHelper = userHelper;
            _context = context;
        }
        //------------------
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        // ---- CREACIÓN DE NUEVO ADMINISTRADOR ------//
            public async Task<IActionResult> Create()
            {
                AddUserViewModel model = new AddUserViewModel
                {
                    Id = Guid.Empty.ToString(),
                    UserType = Enums.UserType.Admin
                };
                return View(model);
            }

            //METODO POST
            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Create(AddUserViewModel model)
            {
                if (ModelState.IsValid)
                {
                    User user = await _userHelper.AddUserAsync(model);
                    if (user == null)
                    {
                        ModelState.AddModelError(string.Empty, "Este correo ya está siendo usado.");
                        return View(model);
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(model);
            } 
        // --------------

        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View(new LoginViewModel());
        }            
    }
}

MajaTours/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MajaTours</title>
    <!-- Favicon -->
    <link rel="shortcut icon" href="Abel.ico" type="image/x-icon">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
     
     <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

      <!-- Libraries Stylesheet -->
    <link href="~/lib/animate/animate.min.css" rel="stylesheet">
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MajaTours.styles.css" asp-append-version="true" />
</head>
<body>
     <!-- Topbar Start -->
    <div class="container-fluid bg-dark px-5 d-none d-lg-block">
        <div class="row gx-0">
            <div class="col-lg-8 text-center text-lg-start mb-2 mb-lg-0">
                <div class="d-inline-flex align-items-center" style="height: 45px;">
                    <small class="me-3 text-light"><i class="fa fa-map-marker-alt me-2"></i>Panamá, Panamá</small>
                    <small class="me-3 text-light"><i class="fa fa-phone-alt me-2"></i>+507 6219 6153</small>
                    <small class="text-light"><i class="fa fa-envelope-open me-2"></i>MajaTours@gmail.com</small>
                </div>
            </div>
            <div class="col-lg-4 text-center text-lg-end">
                <div class="d-inline-flex align-items-center" style="height: 45px;">
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-twitter fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-facebook-f fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-linkedin-in fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-instagram fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle" href=""><i class="fab fa-youtube fw-normal"></i></a>
                </div>
            </div>
        </div>
    </div>
    <!-- Inicio de Menu de Barra-->
       <div class="container-fluid position-relative p-0">
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow ">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="img-fluid" src="images/Logo.png"></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-item nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Políticas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Nosotros</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Servicios</a>
                                <ul class="dropdown-menu m-0">
                                    <a href="destination.html" class="dropdown-item">Tours</a>
                                    <a href="booking.html" class="dropdown-item">Productos Artesanales</a>
                                </ul>
                            </li>
                           
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categorías</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Usuarios</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Productos</a>
                                </li>
                                
                            }
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="ChangeUser">@User.Identity.Name</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Cerrar Sesión</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="btn btn-outline-success py-2 px-4 ms-0" asp-area="" asp-controller="Account" asp-action="Login">Iniciar Sesión</a>
                                </li>
                                  <li class="nav-item">
                                    <a class="btn btn-outline-warning py-2 px-5 ms-1" asp-area="" asp-controller="Account" asp-action="Register">Registrar</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    <!-- Fin Menu -->
    
     <div class="py-5">
            @RenderBody()
    </div>

     <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Compañia</h4>
                    <a class="btn btn-link" href="">Nosotros</a>
                    <a class="btn btn-link" href="">Contactos</a>
                    <a class="btn btn-link" href="">Política de privacidad</a>
                    <a class="btn btn-link" href="">Términos y Condiciones</a>
                    <a class="btn btn-link" href="">Preguntas frecuentes y ayuda</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Contactos</h4>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Panamá, Panamá</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+507 6219 6153</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>MajaTours@gmail.com</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Galerias</h4>
                    <div class="row g-2 pt-2">
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="img/package-1.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="img/package-2.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="img/package-3.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="img/package-2.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="img/package-3.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="img/package-1.jpg" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Boletin informativo</h4>
                    <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <input class="form-control border-primary w-100 py-3 ps-4 pe-5" type="text" placeholder="Su email...">
                        <button type="button" class="btn btn-primary  py-2 position-absolute top-0 end-0 mt-2 me-2">Inscribirse</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; 2022 - MajaTours - <a asp-area="" asp-controller="Home" asp-action="Privacy">Políticas</a>
                    </div>
                    <div class="col-md-6 text-center text-md-end">
                        <div class="footer-menu">
                            <a href="">Inicio</a>
                            <a href="">Cookies</a>
                            <a href="">Ayuda</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MajaTours/Views/Shared/_User.cshtml
@model MajaTours.Models.EditUserViewModel

<div class="row">
    <div class="col-md-6">
        
        <div class="form-group">
            <label asp-for="FirstName" class="control-label"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="LastName" class="control-label"></label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>


        <div class="form-group">
            <label asp-for="PhoneNumber" class="control-label"></label>
            <input asp-for="PhoneNumber" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
    </div>      
</div>